### ISSUE TITLE
HDFS Tested

### ISSUE THREAD

**Issue by irxbacon** [vtrhyno/SEBC#10]
Here we go!

**Comment by irxbacon** [comment]
And getting permission errors... crap

**Comment by irxbacon** [comment]
yay for speculative execution saving my bacon!

**Comment by mfernest** [comment]
All completely fine. My apologies, I don't know how I overlooked this work. Well, I do, but I'm not going to say why publicly. 😩 

Clean work!

**Comment by irxbacon** [comment]
Completely ok, I didn't expect it to change me from provisional to full but I did want to know if my work was valid.
