### ISSUE TITLE
Storage labs

### ISSUE THREAD

**Issue by irxbacon** [vtrhyno/SEBC#2]

**Comment by irxbacon** [comment]
Got replication to work from my cluster to my cluster, ran into AWS IP issues when trying to go to remote cluster.

**Comment by irxbacon** [comment]
Math is hard, 10gig < 1TB.  Corrected and reran this morning

**Comment by irxbacon** [comment]
And... apparently I still can't read.  Didn't create the cache BEFORE the first run.

**Comment by irxbacon** [comment]
https://hadoop.apache.org/docs/r2.4.1/hadoop-project-dist/hadoop-hdfs/CentralizedCacheManagement.html

**Comment by irxbacon** [comment]
Didn't think the caching would reduce run time by nearly 50%, that's pretty cool.

**Comment by mikeridley** [comment]
I'm surprised you were able to reduce the terasort time by 50% with HDFS caching; I wouldn't expect this result to be typical.

**Comment by irxbacon** [comment]
I think the reduction was due to how absurdly long it took in the first place.  I've clearly got something not set up right if it took nearly 40 minutes in the first place.

**Comment by mikeridley** [comment]
Concur - 40 min seems very long for 10 GB on 10 nodes.

**Comment by irxbacon** [comment]
Realized when I set the instances up I made them m3.large not m3.xlarge, resulting in have the memory.  I've shut everything down, increased the size and brought them back up.  This (as expected) did change my public IPs but that's not a big deal.  I'm about to see if everything really came back up.

**Comment by mikeridley** [comment]
Good luck :-).  Historically we have not supported EBS volumes, so therefore we did not support start/stop of instances in the cloud.  As of several months ago, the reference architecture was updated to include support for EBS, but start/stop is still an untested/best of luck to you type thing.

Having said that, we have plenty of customers who do start/stop clusters in AWS but it's not something that we have any particular tooling for.  So...your mileage may vary.

**Comment by irxbacon** [comment]
Well they all came back up, but there's something with the mysql reconnection : opportunities for learning

**Comment by irxbacon** [comment]
Yeah... guess who's rebuilding again

**Comment by mikeridley** [comment]
Learning opportunities :-)

**Comment by mfernest** [comment]
Ayep, learning the learns.

Completed.
