### ISSUE TITLE
Resources

### ISSUE THREAD

**Issue by irxbacon** [vtrhyno/SEBC#3]
![screenshot from 2016-09-21 16 32 06](https://cloud.githubusercontent.com/assets/17276856/18727948/1afdda90-8019-11e6-846d-d447c68b718a.png)

**Comment by irxbacon** [comment]
![screenshot from 2016-09-21 16 40 22](https://cloud.githubusercontent.com/assets/17276856/18728176/25212da0-801a-11e6-9290-af4586ebe74e.png)

**Comment by irxbacon** [comment]
I wasn't sure if the requirement was the status page (which makes sense to me) or the 1/4 page (which is what was stated.

![1_static_pools](https://cloud.githubusercontent.com/assets/17276856/18728198/431e37bc-801a-11e6-8aa8-7605ea4f7006.png)

**Comment by mfernest** [comment]
You got the right page. Apparently my instructions are too fuzzy on this point.

**Comment by mfernest** [comment]
Completed
