### ISSUE TITLE
Install MySQL

### ISSUE THREAD

**Issue by irxbacon** [vtrhyno/SEBC#7]

**Comment by irxbacon** [comment]
Having stupid dependency issues. Glibc 12 is the "latest" as far as yum (after update) is concerned.  Trying to correct

**Comment by irxbacon** [comment]
Cannot get 5.5 to install due to dependency issues.  

Packages skipped because of dependency problems:
    libaio-0.3.107-10.el6.x86_64 from base
    mysql-community-client-5.5.52-2.el7.x86_64 from mysql55-community
    mysql-community-common-5.5.52-2.el7.x86_64 from mysql55-community
    mysql-community-libs-5.5.52-2.el7.x86_64 from mysql55-community
    mysql-community-server-5.5.52-2.el7.x86_64 from mysql55-community
    perl-DBI-1.609-4.el6.x86_64 from base
[root@ip-10-0-1-137 yum.repos.d]# 

Switching to 54.211.194.218 to use mysql 5.1

**Comment by irxbacon** [comment]
Added /etc/yum.repos.d/mysql-community.repo from the NON-WORKING 5.5 install.

**Comment by mfernest** [comment]
I figure the package dependency issues have to do with something in the OS image you used -- not counting that against you.

**Comment by mfernest** [comment]
Completed.
