### ISSUE TITLE
Install CDH

### ISSUE THREAD

**Issue by irxbacon** [vtrhyno/SEBC#9]

**Comment by irxbacon** [comment]
The "warning this will cause issues" concerns me

![screenshot from 2016-09-23 11 20 49](https://cloud.githubusercontent.com/assets/17276856/18791233/daf1de0c-817f-11e6-93ad-ff71795eb4cf.png)

**Comment by irxbacon** [comment]
Realized after the fact that I missed the hive sample data installation.  Just was trying to get to testing and missed that it was needed.  BOOOOO

**Comment by mfernest** [comment]
Sorry man, that's a bummer.

Complete-minus. The range for INC is leaving out a major component. The data is mostly a setup for the following stages.
